name: coastal_threads
version: '1.0.0'

profile: coastal_threads

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  coastal_threads:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
